package bg.energo.phoenix.model.enums.template;

public enum ContractTemplatePurposes {
    INVOICE,
    CANCEL_DISCONNECTION_POWER,
    DEPOSIT,
    EMAIL,
    INVOICE_CANCEL,
    LATE_PAYMENT_FINE,
    MANUAL_LIABILITY_OFFSET,
    OBJECTION_CHANGE_COORD,
    OBJECTION_WITHDRAW_CHANGE_COORD,
    PENALTY,
    PRODUCT,
    RECONNECTION_POWER,
    REMINDER,
    REMINDER_DISCONNECT_POWER,
    REQUEST_DISCONNECT_POWER,
    RESCHEDULING,
    SERVICE,
    SMS,
    TERMINATION,
    ADDITIONAL_AGREEMENT,
    PRODUCT_ADDITIONAL_TEMPLATE_BASE,
    PRODUCT_ADDITIONAL_TEMPLATE_ADVANCE,
    SERVICE_ADDITIONAL_TEMPLATE_BASE,
    SERVICE_ADDITIONAL_TEMPLATE_ADVANCE
}
