stages:
  - dependencies
  - build
  - build-docker
  - deploy
  - notify

variables:
  DOCKER_DRIVER: overlay
  IMAGE_NAME: git.domain.internal/asterbit/phoenix-sales-portal2
  CONTAINER_PORT: 7092
  APP_NAME: phoenix-sales-portal2
  profile: dev

build:
  # image: gradle:7.3.3-jdk17-alpine

  stage: build
  before_script:
    - sudo chown gitlab-runner:gitlab-runner /home/gitlab-runner/builds -R
  script:
    - echo "Clean the code..."
    - sudo sh $CI_PROJECT_DIR/gradlew clean --no-daemon
    - echo "Compiling the code..."
    - sudo sh $CI_PROJECT_DIR/gradlew build --no-daemon
    - sudo chown gitlab-runner:gitlab-runner /home/gitlab-runner/builds -R
  artifacts:
    paths:
      - build/libs/sales-portal-0.0.1-SNAPSHOT.jar
    expire_in: 1 week
  tags:
    #  - dev-runner-docker
    - core-builder
  needs: [ "choose_env" ]

build-docker:
  stage: build-docker
  script:
    - sudo ip a
    - sudo docker build -t $IMAGE_NAME .
  tags:
    - dev-runner-shell
  needs: [ "build" ]

container-deploy:
  stage: deploy
  script:
    - sudo docker rm -f $APP_NAME > /dev/null 2>&1
    - sudo docker run -v /phoenix/xenergy:/usr/share/xEnergie/reports -v /Phxsign_140:/Phxsign_140 -v /phoenix/cert/:/usr/share/certs/ -v /data2:/data -v /phoenix/jsingpdf/:/usr/share/jsingpdf/ -v /usr/share/fonts:/usr/share/fonts --env profile=$profile -d --restart unless-stopped --name $APP_NAME -p $CONTAINER_PORT:8080 $IMAGE_NAME
    - sudo docker system prune -f
  tags:
    - dev-runner-shell
  needs: [ "build-docker" ]


