package bg.energo.phoenix.model.enums.nomenclature;

public enum CustomerAssessmentCriteriaType {
    REMINDERS,
    REQUESTS_FOR_DISCONNECTION_OF_THE_POWER_SUPPLY,
    RESCHEDULING_AGREEMENTS_FOR_THE_LAST_TWELVE_MONTHS,
    ACTIVE_RESCHEDULING_AGREEMENT,
    EXISTENCE_OF_LAWSUITS_WITH_THE_CUSTOMER,
    LIABILITY_FROM_A_PF,
    ACTIVE_REQUEST_FOR_DISCONNECTION,
    CHANGE_OF_OWNERSHIP_IN_THE_LAST_TWELVE_MONTHS,
    INSOLVENCY_AND_LIQUIDATION_CLOSURE
}
