package phoenix.core.exception;

public enum ErrorCode {
    DOMAIN_ENTITY_NOT_FOUND,
    APPLICATION_ERROR,
    ILLEGAL_ARGUMENTS_PROVIDED,
    ACCESS_DENIED,
    UNSUPPORTED_OPERATION,
    OPERATION_NOT_ALLOWED,
    CUSOMER_CREATE_ERROR,
    CONFLICT
}
