-- DELETE Statements for All Tables
DELETE FROM nomenclature.electricity_price_types;
DELETE FROM nomenclature.price_component_value_types;
DELETE FROM terms.term_group_terms;
DELETE FROM price_component.application_models;
DELETE FROM price_component.am_per_piece_ranges;
DELETE FROM price_component.am_over_time_one_times;
DELETE FROM price_component.am_over_time_periodically;
DELETE FROM price_component.am_over_time_periodically_day_week_period_year;
DELETE FROM price_component.am_over_time_periodically_date_of_months;
DELETE FROM price_component.am_over_time_periodically_issuing_periods;
DELETE FROM price_component.am_for_volumes_by_scales;
DELETE FROM price_component.am_for_volumes_by_scale_scales;
DELETE FROM price_component.am_for_volumes_by_scale_issuing_periods;
DELETE FROM price_component.am_for_volumes_by_settlement_periods;
DELETE FROM price_component.am_for_volumes_by_settlement_period_issuing_periods;
DELETE FROM price_component.am_for_volumes_by_settlement_periods_day_week_period_year;
DELETE FROM price_component.am_for_volumes_by_settlement_period_date_of_months;
DELETE FROM price_component.am_for_volumes_by_settlement_period_profiles;
DELETE FROM price_component.am_settlement_periods;
DELETE FROM price_component.am_for_volumes_by_scale_kwh_restriction_ranges;
DELETE FROM price_component.am_for_volumes_by_scale_ccy_restriction_ranges;
DELETE FROM price_component.am_for_volumes_by_settlement_period_ccy_restriction_ranges;
DELETE FROM price_component.am_for_volumes_by_settlement_period_kwh_restriction_ranges;
DELETE FROM service.service_files;
DELETE FROM service_order.order_proxies;
DELETE FROM service_order.order_proxy_files;
DELETE FROM service_order.order_proxy_managers;
DELETE FROM service_order.order_related_product_contracts;
DELETE FROM goods_order.order_proxies;


DELETE FROM receivable.power_supply_reconnection_tasks;
DELETE FROM receivable.power_supply_reconnection_templates;
DELETE FROM receivable.power_supply_reconnection_pods;
DELETE FROM receivable.power_supply_reconnection_files;
DELETE FROM receivable.power_supply_reconnections;
DELETE FROM nomenclature.disconnection_reasons;
DELETE FROM billing.standard_vat_base_details;
DELETE FROM receivable.liabilities_condition_replacemets;
DELETE FROM receivable.customer_deposit_ftp_files;
DELETE FROM receivable.customer_payments;
DELETE FROM product_contract.contract_version_types;
DELETE FROM service_contract.contract_additional_docs;
DELETE FROM service_contract.contract_pods;
DELETE FROM service_contract.contract_related_goods_orders;
DELETE FROM service_contract.contract_related_service_contracts;
DELETE FROM service_contract.contract_related_service_orders;
DELETE FROM service_contract.contract_external_intermediaries;
DELETE FROM sysconfig.runtime_settings;


DELETE FROM nomenclature.nomenclatures;
DELETE FROM nomenclature.countries;
DELETE FROM nomenclature.regions;
DELETE FROM nomenclature.municipalities;
DELETE FROM nomenclature.populated_places;
DELETE FROM nomenclature.districts;
DELETE FROM nomenclature.titles;
DELETE FROM nomenclature.segments;
DELETE FROM nomenclature.banks;
DELETE FROM nomenclature.account_manager_types;
DELETE FROM nomenclature.belonging_capital_owners;
DELETE FROM nomenclature.profiles;
DELETE FROM nomenclature.legal_forms;
DELETE FROM nomenclature.legal_forms_transl;
DELETE FROM nomenclature.economic_branch_ci;
DELETE FROM nomenclature.platforms;
DELETE FROM nomenclature.representation_methods;
DELETE FROM nomenclature.connection_types_rci;
DELETE FROM nomenclature.connection_types_gcc;
DELETE FROM nomenclature.contact_purposes;
DELETE FROM nomenclature.unwanted_customers_reasons;
DELETE FROM nomenclature.ownership_forms;
DELETE FROM nomenclature.economic_branch_ncea;
DELETE FROM nomenclature.zip_codes;
DELETE FROM nomenclature.residential_areas;
DELETE FROM nomenclature.streets;
DELETE FROM nomenclature.credit_ratings;
DELETE FROM nomenclature.preferences;
DELETE FROM nomenclature.system_messages;
DELETE FROM nomenclature.pod_measurement_types;
DELETE FROM nomenclature.scales;

DELETE FROM customer.customers;
DELETE FROM customer.customer_details;
DELETE FROM customer.customer_owners;
DELETE FROM customer.unwanted_customers;
DELETE FROM customer.customer_managers;
DELETE FROM customer.customer_communications;
DELETE FROM customer.customer_comm_contact_persons;
DELETE FROM customer.customer_comm_contact_purposes;
DELETE FROM customer.customer_communication_contacts;
DELETE FROM customer.related_customers;
DELETE FROM customer.customer_segments;
DELETE FROM customer.customer_account_managers;
DELETE FROM customer.connected_groups;
DELETE FROM customer.customer_preferences;
DELETE FROM customer.customer_connected_groups;

DELETE FROM process_management.processed_record_info;
DELETE FROM process_management.process;
DELETE FROM process_management.template;
DELETE FROM customer.account_manager_tags;
DELETE FROM customer.portal_tags;
DELETE FROM customer.account_managers;
DELETE FROM goods.goods_sales_channels;
DELETE FROM goods.goods_sales_areas;
DELETE FROM goods.goods_segments;
DELETE FROM goods.goods_details;
DELETE FROM goods.goods;
DELETE FROM prices.price_parameter_detail_info;
DELETE FROM prices.price_parameter_details;
DELETE FROM prices.price_parameters;
DELETE FROM nomenclature.goods_suppliers;
DELETE FROM nomenclature.goods_groups;
DELETE FROM nomenclature.sales_areas;
DELETE FROM nomenclature.sales_channels;
DELETE FROM nomenclature.currencies;
DELETE FROM nomenclature.vat_rates;
DELETE FROM nomenclature.goods_units;
DELETE FROM nomenclature.product_types;
DELETE FROM nomenclature.price_component_price_types;
DELETE FROM nomenclature.service_units;
DELETE FROM nomenclature.service_types;
DELETE FROM nomenclature.product_groups;
DELETE FROM nomenclature.service_groups;
DELETE FROM nomenclature.calendars;
DELETE FROM nomenclature.holidays;
DELETE FROM nomenclature.grid_operators;
DELETE FROM product.terminations;
DELETE FROM product.termination_notification_channels;
DELETE FROM product.termination_groups;
DELETE FROM product.termination_group_details;
DELETE FROM product.termination_group_terminations;
DELETE FROM terms.term_group_details;
DELETE FROM terms.term_groups;
DELETE FROM terms.terms;
DELETE FROM terms.penalty_groups;
DELETE FROM terms.penalty_group_penalties;
DELETE FROM terms.penalties;
DELETE FROM terms.penalty_payment_terms;
DELETE FROM terms.penalty_group_details;
DELETE FROM terms.invoice_payment_terms;

DELETE FROM product.product_details;
DELETE FROM product.products;
DELETE FROM product.product_consumption_purposes;
DELETE FROM product.product_contract_types;
DELETE FROM product.product_forecastings;
DELETE FROM product.product_pod_metering_types;
DELETE FROM product.product_payment_guarantees;
DELETE FROM product.product_voltage_levels;
DELETE FROM product.product_schedule_registrations;
DELETE FROM product.product_taking_over_balancing_costs;
DELETE FROM product.product_grid_operators;
DELETE FROM product.product_payment_method_limitations;
DELETE FROM product.product_contract_terms;
DELETE FROM product.product_sales_channels;
DELETE FROM product.product_sales_areas;
DELETE FROM product.product_segments;
DELETE FROM product.product_terminations;
DELETE FROM product.product_termination_groups;
DELETE FROM product.product_penalties;
DELETE FROM product.product_penalty_groups;
DELETE FROM product.product_interim_advance_payments;
DELETE FROM product.product_interim_advance_payment_groups;
DELETE FROM product.product_price_components;
DELETE FROM product.product_price_component_groups;
DELETE FROM product.product_linked_products;
DELETE FROM product.product_linked_services;

DELETE FROM service.services;
DELETE FROM service.service_details;

DELETE FROM price_component.price_components;
DELETE FROM price_component.price_component_groups;
DELETE FROM price_component.price_component_group_details;
DELETE FROM price_component.pc_group_pcs;
DELETE FROM price_component.price_component_formula_variables;

DELETE FROM interim_advance_payment.interim_advance_payments;
DELETE FROM interim_advance_payment.interim_advance_payment_terms;
DELETE FROM interim_advance_payment.interim_advance_payment_issuing_periods;
DELETE FROM interim_advance_payment.interim_advance_payment_day_week_period_year;
DELETE FROM interim_advance_payment.interim_advance_payment_date_of_months;
DELETE FROM interim_advance_payment.interim_advance_payment_groups;
DELETE FROM interim_advance_payment.interim_advance_payment_group_details;
DELETE FROM interim_advance_payment.iap_group_iaps;

DELETE FROM service.service_contract_terms;
DELETE FROM service.service_grid_operators;
DELETE FROM service.service_interim_advance_payment_groups;
DELETE FROM service.service_interim_advance_payments;
DELETE FROM service.service_linked_products;
DELETE FROM service.service_linked_services;
DELETE FROM service.service_penalties;
DELETE FROM service.service_penalty_groups;
DELETE FROM service.service_price_component_groups;
DELETE FROM service.service_price_components;
DELETE FROM service.service_sales_areas;
DELETE FROM service.service_sales_channels;
DELETE FROM service.service_segments;
DELETE FROM service.service_termination_groups;
DELETE FROM service.service_terminations;
DELETE FROM product.product_files;
DELETE FROM nomenclature.user_types;
DELETE FROM nomenclature.contract_version_types;
DELETE FROM nomenclature.balancing_group_coordinators;
DELETE FROM pod.pod;
DELETE FROM pod.pod_details;
DELETE FROM pod.discounts;
DELETE FROM pod.discount_pods;
DELETE FROM pod.meters;
DELETE FROM pod.meter_scales;
DELETE FROM pod.billing_by_profile;
DELETE FROM pod.billing_data_by_profile;
DELETE FROM nomenclature.deactivation_purposes;
DELETE FROM nomenclature.bnb_base_interest_rates;


DELETE FROM nomenclature.task_types;
DELETE FROM nomenclature.task_type_stages;
DELETE FROM nomenclature.activity;
DELETE FROM nomenclature.sub_activity;
DELETE FROM nomenclature.campaigns;
DELETE FROM nomenclature.external_intermediaries;


DELETE FROM pod.billing_data_by_scale;
DELETE FROM pod.billing_by_scale;



DELETE FROM interest_rate.interest_rates;
DELETE FROM interest_rate.interest_rate_payment_terms;
DELETE FROM interest_rate.interest_rates_and_periods;


DELETE FROM task.task_files;
DELETE FROM task.tasks;
DELETE FROM task.task_stages;
DELETE FROM task.task_comments;
DELETE FROM task.task_activity;

DELETE FROM customer.customer_tasks;
DELETE FROM customer.customer_activity;

DELETE FROM product_contract.contracts;
DELETE FROM product_contract.contract_tasks;
DELETE FROM product_contract.contract_activity;
DELETE FROM product_contract.contract_details;
DELETE FROM product_contract.contract_internal_intermediaries;
DELETE FROM product_contract.contract_external_intermediaries;
DELETE FROM product_contract.contract_files;
DELETE FROM product_contract.contract_additional_docs;
DELETE FROM product_contract.contract_billing_groups;

DELETE FROM service_contract.contracts;
DELETE FROM service_contract.contract_tasks;
DELETE FROM service_contract.contract_activity;
DELETE FROM service_contract.contract_details;


DELETE FROM activity.activity;
DELETE FROM activity.activity_files;


DELETE FROM action.action_liabilities;
DELETE FROM product.product_for_balancing;
DELETE FROM service_order.order_unrecognized_pods;
DELETE FROM service_order.order_related_service_orders;
DELETE FROM service_order.order_related_service_contracts;
DELETE FROM service_order.order_related_goods_orders;
DELETE FROM service_order.order_tasks;
DELETE FROM service_order.order_linked_service_contracts;
DELETE FROM service_order.order_linked_product_contracts;
DELETE FROM service_order.order_pods;
DELETE FROM service_order.order_internal_intermediaries;
DELETE FROM service_order.order_external_intermediaries;
DELETE FROM service_order.order_assisting_employees;
DELETE FROM service_order.order_price_components;
DELETE FROM service_order.order_activity;
DELETE FROM action.action_files;
DELETE FROM action.action_pods;
DELETE FROM product_contract.contract_proxy_managers;
DELETE FROM product_contract.contract_proxy_files;
DELETE FROM product_contract.contract_proxies;
DELETE FROM product_contract.contract_related_goods_orders;
DELETE FROM product_contract.contract_related_service_contracts;
DELETE FROM product_contract.contract_related_service_orders;
DELETE FROM product_contract.contract_related_product_contracts;
DELETE FROM product_contract.contract_assisting_employees;
DELETE FROM product_contract.contract_pods;
DELETE FROM goods_order.order_goods;
DELETE FROM goods_order.order_payment_terms;
DELETE FROM goods_order.order_related_service_orders;
DELETE FROM goods_order.order_related_service_contracts;
DELETE FROM goods_order.order_related_product_contracts;
DELETE FROM goods_order.order_related_goods_orders;
DELETE FROM goods_order.order_tasks;
DELETE FROM goods_order.order_external_intermediaries;
DELETE FROM goods_order.order_internal_intermediaries;
DELETE FROM goods_order.order_assisting_employees;
DELETE FROM goods_order.order_activity;
DELETE FROM nomenclature.action_types;
DELETE FROM action.actions;
DELETE FROM service_contract.contract_files;
DELETE FROM service_contract.contract_proxy_managers;
DELETE FROM service_contract.contract_proxy_files;
DELETE FROM service_contract.contract_proxies;
DELETE FROM service_contract.contract_unrecognized_pods;
DELETE FROM service_contract.contract_linked_product_contracts;
DELETE FROM service_contract.contract_linked_service_contracts;
DELETE FROM service_contract.contract_assisting_employees;
DELETE FROM service_contract.contract_internal_intermediaries;
DELETE FROM service_contract.contract_version_types;
DELETE FROM service_order.orders;
DELETE FROM goods_order.orders;
DELETE FROM service_contract.contract_price_components;
DELETE FROM service_contract.contract_iap_price_components;
DELETE FROM service_contract.contract_interim_advance_payments;

DELETE FROM nomenclature.prefixes;
DELETE FROM company.companies;
DELETE FROM company.company_details;
DELETE FROM company.company_logos;
DELETE FROM company.company_banks;
DELETE FROM company.company_communication_addresses;
DELETE FROM company.company_emails;
DELETE FROM company.company_invoice_compilers;
DELETE FROM company.company_invoice_issue_places;
DELETE FROM company.company_managers;
DELETE FROM company.company_telephones;
DELETE FROM billing.account_periods;
DELETE FROM billing.account_period_status_change_hist;
DELETE FROM billing.account_period_sap_report;
DELETE FROM billing.account_period_vat_dairy_report;
DELETE FROM billing.billings;
DELETE FROM billing.process_periodicity;
DELETE FROM billing.process_periodicity_day_of_months;
DELETE FROM billing.process_periodicity_incompatible_billings;
DELETE FROM billing.process_periodicity_issuing_periods;
DELETE FROM billing.process_periodicity_period_of_year;
DELETE FROM billing.process_periodicity_time_intervals;
DELETE FROM billing.billing_process_periodicity;
DELETE FROM billing.billing_contract_billing_groups;
DELETE FROM billing.billing_summary_data;
DELETE FROM billing.billing_detailed_data;
DELETE FROM billing.billing_tasks;
DELETE FROM billing.billing_invoices;
DELETE FROM invoice.invoices;
DELETE FROM invoice.invoice_detailed_data;
DELETE FROM invoice.invoice_vat_rate_values;
DELETE FROM invoice.invoice_standard_detailed_data_vat_base;
DELETE FROM invoice.invoice_total_actual_consumption;
DELETE FROM nomenclature.risk_assessments;
DELETE FROM product_contract.contract_interim_advance_payments;
DELETE FROM process_management.process_contract_pods;
DELETE FROM price_component.profile_for_balancing;
DELETE FROM product.product_additional_params;

DELETE FROM receivable.customer_assessment_tasks;
DELETE FROM receivable.customer_assessment_add_conditions;
DELETE FROM receivable.customer_assessments;
DELETE FROM receivable.power_supply_disconnection_reminder_customers;
DELETE FROM receivable.power_supply_disconnection_reminder_tasks;
DELETE FROM receivable.power_supply_disconnection_reminders;
DELETE FROM receivable.customer_receivables;
DELETE FROM receivable.mlo_customer_receivables;
DELETE FROM receivable.customer_liabilities;
DELETE FROM receivable.mlo_customer_liabilities;
DELETE FROM receivable.late_payment_fine_communications;
DELETE FROM receivable.late_payment_fine_ftp_files;
DELETE FROM receivable.late_payment_fines;
DELETE FROM receivable.mlo_customer_deposits;
DELETE FROM receivable.customer_deposits;
DELETE FROM receivable.manual_liabilitie_offsettings;
DELETE FROM receivable.payment_packages;
DELETE FROM receivable.collection_channel_banks;
DELETE FROM receivable.collection_channel_priority_liab_prefixes;
DELETE FROM receivable.collection_channel_exclude_liab_prefixes;
DELETE FROM receivable.collection_channels;
DELETE FROM nomenclature.additional_conditions;
DELETE FROM nomenclature.customer_assessment_types;
DELETE FROM nomenclature.cancelation_reasons;
DELETE FROM nomenclature.grounds_for_objection_withdrawal_to_change_of_cbg;
DELETE FROM nomenclature.balancing_group_coordinator_grounds;
DELETE FROM nomenclature.collection_partners;
DELETE FROM nomenclature.blocking_reasons;
DELETE FROM receivable.mass_operation_for_blocking_exclution_prefixes;
DELETE FROM receivable.mass_operation_for_blocking;
DELETE FROM service_contract.contract_service_additional_params;
DELETE FROM product_contract.contract_product_additional_params;
DELETE FROM service.service_additional_params;
DELETE FROM terms.penalty_action_types;
DELETE FROM billing.billing_invoice_files;
DELETE FROM receivable.objection_withdrawal_to_change_of_cbg_tasks;
DELETE FROM receivable.objection_withdrawal_to_change_of_cbg_email_templates;
DELETE FROM receivable.objection_withdrawal_to_change_of_cbg_doc_templates;
DELETE FROM receivable.objection_withdrawal_to_change_of_cbg_process_results;
DELETE FROM receivable.objection_withdrawal_to_change_of_cbg;


DELETE FROM nomenclature.sms_sending_numbers;
DELETE FROM nomenclature.rps_numbers;
DELETE FROM nomenclature.communication_topics;
DELETE FROM crm.email_communications;
DELETE FROM crm.email_communication_customers;
DELETE FROM crm.onpaper_communication_files;
DELETE FROM crm.onpaper_communications;
DELETE FROM process_management.process_files;
DELETE FROM invoice.invoice_reversal_invoice;
DELETE FROM billing.billing_error_data;
DELETE FROM product.product_details_collection_channels;
DELETE FROM product.product_contract_templates;
DELETE FROM service.service_details_collection_channels;
DELETE FROM template.templates;
DELETE FROM template.template_files;
DELETE FROM template.template_details;
DELETE FROM product.product_templates;
DELETE FROM service.service_templates;
DELETE FROM template.document_file;
DELETE FROM template.document;
DELETE FROM product.termination_templates;
DELETE FROM terms.penalty_templates;
DELETE FROM billing.billing_templates;
DELETE FROM invoice.invoice_cancelation_templates;
DELETE FROM receivable.power_supply_disconnection_request_templates;
DELETE FROM receivable.power_supply_dcn_cancellations;
DELETE FROM receivable.objection_withdrawal_to_change_of_cbg_templates;
DELETE FROM receivable.power_supply_dcn_cancellation_templates;
DELETE FROM receivable.power_supply_disconnections;
DELETE FROM nomenclature.document_expiration_period;
DELETE FROM invoice.invoice_documents;
DELETE FROM receivable.power_supply_disconnection_reminder_templates;
DELETE FROM receivable.customer_deposit_payment_ddl_aft_withdrawal;
DELETE FROM action.action_templates;
DELETE FROM process_management.process_notification;
DELETE FROM billing.billing_notifications;
DELETE FROM notification.user_notifications;
DELETE FROM receivable.reminders;
DELETE FROM crm.email_communication_contact_purposes;
DELETE FROM receivable.power_supply_disconnection_requests;
DELETE FROM receivable.power_supply_disconnection_request_pods;
DELETE FROM receivable.power_supply_disconnection_request_pod_liabilities;
DELETE FROM receivable.reschedulings;
DELETE FROM receivable.rescheduling_agreement_templates;
DELETE FROM receivable.rescheduling_files;
DELETE FROM receivable.rescheduling_liabilities;
DELETE FROM receivable.rescheduling_plans;
DELETE FROM receivable.rescheduling_tasks;
DELETE FROM receivable.rescheduling_signable_documents;
DELETE FROM receivable.objection_to_change_of_cbg_email_templates;
DELETE FROM receivable.objection_to_change_of_cbg_templates;
DELETE FROM receivable.objection_to_change_of_cbg_sub_files;
DELETE FROM receivable.objection_to_change_of_cbg_pods;
DELETE FROM receivable.objection_to_change_of_cbg_tasks;
DELETE FROM receivable.objection_to_change_of_cbg;

DELETE FROM receivable.objection_to_change_of_cbg_doc_templates;
DELETE FROM receivable.objection_to_change_of_cbg_files;
DELETE FROM receivable.objection_to_change_of_cbg_process_results;
DELETE FROM receivable.power_supply_dcn_cancellation_tasks;
DELETE FROM receivable.power_supply_dcn_cancellation_pods;
DELETE FROM receivable.power_supply_dcn_cancellation_files;
DELETE FROM nomenclature.grid_operator_taxes;
DELETE FROM invoice.manual_invoice_summary_data;
DELETE FROM invoice.manual_invoice_detailed_data;
DELETE FROM billing.billing_run_draft_invoices_marks;
DELETE FROM billing.billing_run_draft_pdf_invoices_marks;
DELETE FROM product_contract.contract_price_components;
DELETE FROM invoice.invoice_standard_detailed_data;
DELETE FROM invoice.manual_debit_or_credit_note_invoice_detailed_data;
DELETE FROM invoice.manual_debit_or_credit_note_invoice_summary_data;
DELETE FROM invoice.invoice_cancelations;
DELETE FROM nomenclature.income_account;
DELETE FROM crm.sms_communications;
DELETE FROM crm.sms_communication_tasks;
DELETE FROM crm.sms_communication_sms_templates;
DELETE FROM crm.sms_communication_related_customers;
DELETE FROM crm.sms_communication_files;
DELETE FROM crm.sms_communication_customers;
DELETE FROM receivable.customer_payment_receivable_offsettings;
DELETE FROM crm.sms_communication_customer_contacts;
DELETE FROM crm.sms_communication_contact_purposes;
DELETE FROM crm.sms_communication_activity;
DELETE FROM receivable.customer_deposit_service_orders;
DELETE FROM receivable.customer_deposit_service_contracts;
DELETE FROM receivable.customer_deposit_product_contracts;
DELETE FROM receivable.customer_deposit_email_templates;
DELETE FROM receivable.customer_deposit_goods_orders;
DELETE FROM receivable.late_payment_fine_invoices;
DELETE FROM invoice.invoice_cancellation_documents;
DELETE FROM nomenclature.pod_additional_params;
DELETE FROM invoice.invoice_cancellation_numbers;
DELETE FROM invoice.invoice_document_files;
DELETE FROM receivable.power_supply_disconnection_reminder_doc_files;
DELETE FROM billing.billing_invoice_sum_files;
DELETE FROM nomenclature.missing_customer;
DELETE FROM action.action_signable_documents;
DELETE FROM lock.locks;
DELETE FROM invoice.invoice_number_generator;
DELETE FROM billing.compensations;
DELETE FROM receivable.customer_receivable_transactions;
DELETE FROM receivable.rescheduling_draft_liabilities;
DELETE FROM receivable.mlo_customer_negative_payments;
DELETE FROM reporting.pod_consumption_cach;
DELETE FROM receivable.late_payment_fine_tasks;

-- RESET (RESTART) Statements for All Sequences

ALTER SEQUENCE nomenclature.electricity_price_types_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.price_component_value_types_id_seq RESTART WITH 1;
ALTER SEQUENCE terms.groups_id_seq RESTART WITH 1;
ALTER SEQUENCE terms.group_details_id_seq RESTART WITH 1;
ALTER SEQUENCE terms.term_group_terms_id_seq RESTART WITH 1;
ALTER SEQUENCE price_component.application_models_id_seq RESTART WITH 1;
ALTER SEQUENCE price_component.application_model_per_piece_ranges_id_seq RESTART WITH 1;
ALTER SEQUENCE price_component.application_model_over_time_one_time_id_seq RESTART WITH 1;
ALTER SEQUENCE price_component.am_over_time_periodically_id_seq RESTART WITH 1;
ALTER SEQUENCE price_component.am_over_time_periodically_day_week_period_year_id_seq RESTART WITH 1;
ALTER SEQUENCE price_component.am_over_time_periodically_date_of_months_id_seq RESTART WITH 1;
ALTER SEQUENCE price_component.am_over_time_periodically_issuing_periods_id_seq RESTART WITH 1;
ALTER SEQUENCE price_component.am_for_volumes_by_scales_id_seq RESTART WITH 1;
ALTER SEQUENCE price_component.am_for_volumes_by_scale_scales_id_seq RESTART WITH 1;
ALTER SEQUENCE price_component.am_for_volumes_by_scale_issuing_periods_id_seq RESTART WITH 1;
ALTER SEQUENCE price_component.am_for_volumes_by_settlement_periods_id_seq RESTART WITH 1;
ALTER SEQUENCE price_component.am_for_volumes_by_settlement_periods_day_week_period_yea_id_seq RESTART WITH 1;
ALTER SEQUENCE price_component.am_for_volumes_by_settlement_period_date_of_months_id_seq RESTART WITH 1;
ALTER SEQUENCE price_component.am_for_volumes_by_settlement_period_profiles_id_seq RESTART WITH 1;
ALTER SEQUENCE price_component.am_settlement_periods_id_seq RESTART WITH 1;
ALTER SEQUENCE price_component.am_for_volume_by_scale_kwh_restriction_ranges_id_seq RESTART WITH 1;
ALTER SEQUENCE price_component.am_for_volumes_by_scale_ccy_restriction_ranges_id_seq RESTART WITH 1;
ALTER SEQUENCE price_component.am_for_volumes_by_settlement_period_ccy_restriction_rang_id_seq RESTART WITH 1;
ALTER SEQUENCE price_component.am_for_volumes_by_settlement_period_kwh_restriction_rang_id_seq RESTART WITH 1;
ALTER SEQUENCE service.service_files_id_seq RESTART WITH 1;
ALTER SEQUENCE product_contract.contract_assisting_employees_id_seq RESTART WITH 1;
ALTER SEQUENCE service_order.order_proxies_id_seq RESTART WITH 1;
ALTER SEQUENCE service_order.order_proxy_files_id_seq RESTART WITH 1;
ALTER SEQUENCE service_order.order_proxy_managers_id_seq RESTART WITH 1;
ALTER SEQUENCE service_order.order_related_goods_orders_id_seq RESTART WITH 1;
ALTER SEQUENCE service_order.order_tasks_id_seq RESTART WITH 1;
ALTER SEQUENCE service_order.order_linked_service_contracts_id_seq RESTART WITH 1;
ALTER SEQUENCE service_order.order_linked_product_contracts_id_seq RESTART WITH 1;


ALTER SEQUENCE invoice.invoice_document_files_id_seq  RESTART WITH 1;
ALTER SEQUENCE invoice.manual_debit_or_credit_note_invoice_summery_data_id_seq  RESTART WITH 1;
ALTER SEQUENCE nomenclature.document_expiration_period_id_seq  RESTART WITH 1;
ALTER SEQUENCE receivable.customer_deposit_ftp_files_id_seq  RESTART WITH 1;
ALTER SEQUENCE nomenclature_additional_conditions_id_seq  RESTART WITH 1;
ALTER SEQUENCE nomenclature_customer_assessment_types_id_seq  RESTART WITH 1;
ALTER SEQUENCE product.product_for_balancing_id_seq  RESTART WITH 1;
ALTER SEQUENCE service_contract.contract_interim_advance_payments_id_seq  RESTART WITH 1;
ALTER SEQUENCE service_contract.contract_additional_docs_id_seq  RESTART WITH 1;
ALTER SEQUENCE service_contract.contract_external_intermediaries_id_seq  RESTART WITH 1;
ALTER SEQUENCE goods_order.order_payment_terms_id_seq  RESTART WITH 1;
ALTER SEQUENCE goods_order.order_external_intermediaries_id_seq  RESTART WITH 1;
ALTER SEQUENCE invoice.invoice_document_files_id_seq  RESTART WITH 1;
ALTER SEQUENCE invoice.manual_debit_or_credit_note_invoice_summery_data_id_seq  RESTART WITH 1;
ALTER SEQUENCE nomenclature.document_expiration_period_id_seq  RESTART WITH 1;
ALTER SEQUENCE receivable.customer_deposit_ftp_files_id_seq  RESTART WITH 1;
ALTER SEQUENCE nomenclature_additional_conditions_id_seq  RESTART WITH 1;
ALTER SEQUENCE nomenclature_customer_assessment_types_id_seq  RESTART WITH 1;
ALTER SEQUENCE product.product_for_balancing_id_seq  RESTART WITH 1;
ALTER SEQUENCE service_contract.contract_interim_advance_payments_id_seq  RESTART WITH 1;
ALTER SEQUENCE service_contract.contract_additional_docs_id_seq  RESTART WITH 1;
ALTER SEQUENCE service_contract.contract_external_intermediaries_id_seq  RESTART WITH 1;
ALTER SEQUENCE goods_order.order_payment_terms_id_seq  RESTART WITH 1;
ALTER SEQUENCE goods_order.order_external_intermediaries_id_seq  RESTART WITH 1;


ALTER SEQUENCE nomenclature.countries_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.regions_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.municipalities_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.populated_places_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.districts_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.titles_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.segments_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.banks_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.account_manager_types_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.belonging_capital_owners_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.profiles_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.legal_forms_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.legal_forms_transl_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.economic_branch_ci_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.platforms_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.representation_methods_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.connection_types_rci_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.connection_types_gcc_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.contact_purposes_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.unwanted_customers_reasons_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.ownership_forms_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.economic_branch_ncea_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.zip_codes_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.residential_areas_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.streets_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.credit_ratings_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.preferences_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.system_messages_id_seq RESTART WITH 1;

ALTER SEQUENCE customer.customers_id_seq RESTART WITH 1;
ALTER SEQUENCE customer.customer_owners_id_seq RESTART WITH 1;
ALTER SEQUENCE customer.unwanted_customers_id_seq RESTART WITH 1;
ALTER SEQUENCE customer.customer_managers_id_seq RESTART WITH 1;
ALTER SEQUENCE customer.customer_communications_id_seq RESTART WITH 1;
ALTER SEQUENCE customer.customer_comm_contact_persons_id_seq RESTART WITH 1;
ALTER SEQUENCE customer.customer_comm_contact_purposes_id_seq RESTART WITH 1;
ALTER SEQUENCE customer.customer_communication_contacts_id_seq RESTART WITH 1;
ALTER SEQUENCE customer.related_customers_id_seq RESTART WITH 1;
ALTER SEQUENCE customer.customer_segments_id_seq RESTART WITH 1;
ALTER SEQUENCE customer.customer_account_managers_id_seq RESTART WITH 1;
ALTER SEQUENCE customer.connected_groups_id_seq RESTART WITH 1;
ALTER SEQUENCE customer.customer_preferences_id_seq RESTART WITH 1;
ALTER SEQUENCE customer.customer_connected_groups_id_seq RESTART WITH 1;

ALTER SEQUENCE process_management.process_id_seq RESTART WITH 1;
ALTER SEQUENCE process_management.processed_record_id_seq RESTART WITH 1;
ALTER SEQUENCE customer.account_managers_id_seq RESTART WITH 1;
ALTER SEQUENCE goods.goods_id_seq RESTART WITH 1;
ALTER SEQUENCE goods.goods_details_id_seq RESTART WITH 1;
ALTER SEQUENCE goods.goods_sales_channels_id_seq RESTART WITH 1;
ALTER SEQUENCE goods.goods_sales_areas_id_seq RESTART WITH 1;
ALTER SEQUENCE goods.goods_segments_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.goods_suppliers_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.goods_groups_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.sales_areas_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.sales_channels_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.currencies_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.vat_rates_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.goods_units_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.product_types_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.price_component_price_types_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.service_units_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.service_groups_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.product_groups_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.holidays_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.calendars_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.grid_operators_id_seq RESTART WITH 1;
ALTER SEQUENCE prices.price_parameters_id_seq RESTART WITH 1;
ALTER SEQUENCE prices.price_parameter_details_id_seq RESTART WITH 1;
ALTER SEQUENCE prices.price_parameter_detail_info_id_seq RESTART WITH 1;


ALTER SEQUENCE terms.terms_id_seq RESTART WITH 1;

ALTER SEQUENCE terms.invoice_payment_terms_id_seq RESTART WITH 1;
ALTER SEQUENCE product.terminations_id_seq RESTART WITH 1;
ALTER SEQUENCE product.termination_notification_channels_id_seq RESTART WITH 1;

ALTER SEQUENCE product.termination_groups_id_seq RESTART WITH 1;

ALTER SEQUENCE product.termination_group_details_id_seq RESTART WITH 1;
ALTER SEQUENCE product.termination_group_terminations_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.service_types_id_seq RESTART WITH 1;

ALTER SEQUENCE product.product_details_id_seq RESTART WITH 1;
ALTER SEQUENCE product.product_id_seq RESTART WITH 1;
ALTER SEQUENCE product.product_consumption_purposes_id_seq RESTART WITH 1;
ALTER SEQUENCE product.product_detail_contract_types_id_seq RESTART WITH 1;
ALTER SEQUENCE product.product_forecastings_id_seq RESTART WITH 1;
ALTER SEQUENCE product.product_pod_metering_types_id_seq RESTART WITH 1;
ALTER SEQUENCE product.product_payment_guarantees_id_seq RESTART WITH 1;
ALTER SEQUENCE product.product_detail_voltage_levels_id_seq RESTART WITH 1;
ALTER SEQUENCE product.product_schedule_registrations_id_seq RESTART WITH 1;
ALTER SEQUENCE product.product_taking_over_balancing_costs_id_seq RESTART WITH 1;
ALTER SEQUENCE product.product_grid_operators_id_seq RESTART WITH 1;
ALTER SEQUENCE product.product_payment_method_limitations_id_seq RESTART WITH 1;
ALTER SEQUENCE product.product_contract_terms_id_seq RESTART WITH 1;
ALTER SEQUENCE product.product_sales_channels_id_seq RESTART WITH 1;
ALTER SEQUENCE product.product_sales_areas_id_seq RESTART WITH 1;
ALTER SEQUENCE product.product_segments_id_seq RESTART WITH 1;
ALTER SEQUENCE product.product_terminations_id_seq RESTART WITH 1;
ALTER SEQUENCE product.product_termination_groups_id_seq RESTART WITH 1;
ALTER SEQUENCE product.product_penalties_id_seq RESTART WITH 1;
ALTER SEQUENCE product.product_penalty_groups_id_seq RESTART WITH 1;
ALTER SEQUENCE product.product_interim_advance_payments_id_seq RESTART WITH 1;
ALTER SEQUENCE product.product_interim_advance_payment_groups_id_seq RESTART WITH 1;
ALTER SEQUENCE product.product_price_components_id_seq RESTART WITH 1;
ALTER SEQUENCE product.product_price_component_groups_id_seq RESTART WITH 1;
ALTER SEQUENCE product.product_linked_products_id_seq RESTART WITH 1;
ALTER SEQUENCE product.product_linked_services_id_seq RESTART WITH 1;

ALTER SEQUENCE service.services_id_seq RESTART WITH 1;
ALTER SEQUENCE service.service_details_id_seq RESTART WITH 1;

ALTER SEQUENCE price_component.price_components_id_seq RESTART WITH 1;
ALTER SEQUENCE price_component.price_component_groups_id_seq RESTART WITH 1;
ALTER SEQUENCE price_component.price_component_group_details_id_seq RESTART WITH 1;
ALTER SEQUENCE price_component.pc_group_pcs_id_seq RESTART WITH 1;
ALTER SEQUENCE price_component.price_component_formula_variables_id_seq RESTART WITH 1;

ALTER SEQUENCE interim_advance_payment.interim_advance_payments_id_seq RESTART WITH 1;
ALTER SEQUENCE interim_advance_payment.interim_advance_payment_terms_id_seq RESTART WITH 1;
ALTER SEQUENCE interim_advance_payment.interim_advance_payment_issuing_periods_id_seq RESTART WITH 1;
ALTER SEQUENCE interim_advance_payment.interim_advance_payment_day_week_period_year_id_seq RESTART WITH 1;
ALTER SEQUENCE interim_advance_payment.interim_advance_payment_date_of_months_id_seq RESTART WITH 1;
ALTER SEQUENCE interim_advance_payment.interim_advance_payment_groups_id_seq RESTART WITH 1;
ALTER SEQUENCE interim_advance_payment.interim_advance_payment_group_details_id_seq RESTART WITH 1;
ALTER SEQUENCE interim_advance_payment.iap_group_iaps_id_seq RESTART WITH 1;

ALTER SEQUENCE service.service_contract_terms_id_seq RESTART WITH 1;
ALTER SEQUENCE service.service_grid_operators_id_seq RESTART WITH 1;
ALTER SEQUENCE service.service_interim_advance_payment_groups_id_seq RESTART WITH 1;
ALTER SEQUENCE service.service_interim_advance_payments_id_seq RESTART WITH 1;
ALTER SEQUENCE service.service_linked_products_id_seq RESTART WITH 1;
ALTER SEQUENCE service.service_linked_services_id_seq RESTART WITH 1;
ALTER SEQUENCE service.service_penalties_id_seq RESTART WITH 1;
ALTER SEQUENCE service.service_penalty_groups_id_seq RESTART WITH 1;
ALTER SEQUENCE service.service_price_component_groups_id_seq RESTART WITH 1;
ALTER SEQUENCE service.service_price_components_id_seq RESTART WITH 1;
ALTER SEQUENCE service.service_sales_areas_id_seq RESTART WITH 1;
ALTER SEQUENCE service.service_sales_channels_id_seq RESTART WITH 1;
ALTER SEQUENCE service.service_segments_id_seq RESTART WITH 1;
ALTER SEQUENCE service.service_termination_groups_id_seq RESTART WITH 1;
ALTER SEQUENCE service.service_terminations_id_seq RESTART WITH 1;


ALTER SEQUENCE nomenclature.user_types_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.contract_version_types_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.balancing_group_coordinators_id_seq RESTART WITH 1;

ALTER SEQUENCE pod.pod_id_seq RESTART WITH 1;
ALTER SEQUENCE pod.pod_details_id_seq RESTART WITH 1;
ALTER SEQUENCE pod.discounts_id_seq RESTART WITH 1;
ALTER SEQUENCE pod.meters_id_seq RESTART WITH 1;
ALTER SEQUENCE pod.meter_scales_id_seq RESTART WITH 1;
ALTER SEQUENCE pod.billing_by_profile_id_seq RESTART WITH 1;
ALTER SEQUENCE pod.billing_data_by_profile_id_seq RESTART WITH 1;

ALTER SEQUENCE nomenclature.deactivation_purposes_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.bnb_base_interest_rates_id_seq RESTART WITH 1;

ALTER SEQUENCE nomenclature.task_types_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.task_type_stages_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.activity_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.sub_activity_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.campaigns_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.external_intermediaries_id_seq RESTART WITH 1;


ALTER SEQUENCE pod.billing_by_scale_id_seq RESTART WITH 1;
ALTER SEQUENCE pod.billing_data_by_scale_id_seq RESTART WITH 1;

ALTER SEQUENCE interest_rate.interest_ratess_id_seq RESTART WITH 1;
ALTER SEQUENCE interest_rate.interest_rate_payment_terms_id_seq RESTART WITH 1;
ALTER SEQUENCE interest_rate.interest_rate_rates_and_periods_id_seq RESTART WITH 1;

ALTER SEQUENCE task.task_files_id_seq RESTART WITH 1;
ALTER SEQUENCE task.tasks_id_seq RESTART WITH 1;
ALTER SEQUENCE task.task_stages_id_seq RESTART WITH 1;
ALTER SEQUENCE task.task_comments_id_seq RESTART WITH 1;
ALTER SEQUENCE task.task_activity_id_seq RESTART WITH 1;

ALTER SEQUENCE customer.customer_tasks_id_seq RESTART WITH 1;
ALTER SEQUENCE customer.customer_activity_id_seq RESTART WITH 1;

ALTER SEQUENCE product_contract.contracts_id_seq RESTART WITH 1;
ALTER SEQUENCE product_contract.contract_number_seq RESTART WITH 1;
ALTER SEQUENCE product_contract.contract_internal_intermediaries_id_seq RESTART WITH 1;
ALTER SEQUENCE product_contract.contract_external_intermediaries_id_seq RESTART WITH 1;
ALTER SEQUENCE product_contract.related_contracts_id_seq RESTART WITH 1;
ALTER SEQUENCE product_contract.contract_pods_id_seq RESTART WITH 1;
ALTER SEQUENCE product_contract.contract_tasks_id_seq RESTART WITH 1;
ALTER SEQUENCE product_contract.contract_activity_id_seq RESTART WITH 1;
ALTER SEQUENCE product_contract.contract_details_id_seq RESTART WITH 1;
ALTER SEQUENCE product_contract.contract_files_id_seq RESTART WITH 1;
ALTER SEQUENCE product_contract.contract_additional_docs_id_seq RESTART WITH 1;

ALTER SEQUENCE service_contract.contracts_id_seq RESTART WITH 1;
ALTER SEQUENCE service_contract.contract_number_seq RESTART WITH 1;
ALTER SEQUENCE service_contract.contract_tasks_id_seq RESTART WITH 1;
ALTER SEQUENCE service_contract.contract_activity_id_seq RESTART WITH 1;
ALTER SEQUENCE service_contract.contract_details_id_seq RESTART WITH 1;

ALTER SEQUENCE activity.activity_id_seq RESTART WITH 1;
ALTER SEQUENCE activity.activity_files_id_seq RESTART WITH 1;

ALTER SEQUENCE product_contract.contract_related_service_orders_id_seq RESTART WITH 1;
ALTER SEQUENCE product_contract.contract_related_service_contracts_id_seq RESTART WITH 1;
ALTER SEQUENCE product_contract.contract_related_goods_orders_id_seq RESTART WITH 1;
ALTER SEQUENCE sysconfig.runtime_settings_id_seq RESTART WITH 1;
ALTER SEQUENCE product_contract.contract_proxies_id_seq RESTART WITH 1;
ALTER SEQUENCE product_contract.contract_proxy_files_id_seq RESTART WITH 1;
ALTER SEQUENCE product_contract.contract_proxy_managers_id_seq RESTART WITH 1;
ALTER SEQUENCE product_contract.contract_version_types_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.action_types_id_seq RESTART WITH 1;
ALTER SEQUENCE action.actions_id_seq RESTART WITH 1;
ALTER SEQUENCE action.action_files_id_seq RESTART WITH 1;
ALTER SEQUENCE action.action_pods_id_seq RESTART WITH 1;
ALTER SEQUENCE action.action_liabilities_id_seq RESTART WITH 1;
ALTER SEQUENCE goods_order.orders_id_seq RESTART WITH 1;
ALTER SEQUENCE goods_order.order_related_service_orders_id_seq RESTART WITH 1;
ALTER SEQUENCE goods_order.order_related_service_contracts_id_seq RESTART WITH 1;
ALTER SEQUENCE goods_order.order_related_product_contracts_id_seq RESTART WITH 1;
ALTER SEQUENCE goods_order.order_related_goods_orders_id_seq RESTART WITH 1;
ALTER SEQUENCE goods_order.order_tasks_id_seq RESTART WITH 1;
ALTER SEQUENCE goods_order.order_proxies_id_seq RESTART WITH 1;
ALTER SEQUENCE goods_order.order_internal_intermediaries_id_seq RESTART WITH 1;
ALTER SEQUENCE goods_order.order_assisting_employees_id_seq RESTART WITH 1;
ALTER SEQUENCE goods_order.order_activity_id_seq RESTART WITH 1;
ALTER SEQUENCE goods_order.order_goods_id_seq RESTART WITH 1;
ALTER SEQUENCE service_order.orders_id_seq RESTART WITH 1;
ALTER SEQUENCE service_order.order_number_seq RESTART WITH 1;
ALTER SEQUENCE service_order.order_related_service_contracts_id_seq RESTART WITH 1;
ALTER SEQUENCE service_order.order_related_product_contracts_id_seq RESTART WITH 1;
ALTER SEQUENCE service_order.order_related_service_orders_id_seq RESTART WITH 1;
ALTER SEQUENCE service_order.order_pods_id_seq RESTART WITH 1;
ALTER SEQUENCE service_order.order_activity_id_seq RESTART WITH 1;
ALTER SEQUENCE service_order.order_assisting_employees_id_seq RESTART WITH 1;
ALTER SEQUENCE service_order.order_price_components_id_seq RESTART WITH 1;
ALTER SEQUENCE service_order.order_unrecognized_pods_id_seq RESTART WITH 1;
ALTER SEQUENCE service_order.order_external_intermediaries_id_seq RESTART WITH 1;
ALTER SEQUENCE service_order.order_internal_intermediaries_id_seq RESTART WITH 1;
ALTER SEQUENCE service_contract.contract_files_id_seq RESTART WITH 1;
ALTER SEQUENCE service_contract.contract_proxies_id_seq RESTART WITH 1;
ALTER SEQUENCE service_contract.contract_proxy_files_id_seq RESTART WITH 1;
ALTER SEQUENCE service_contract.contract_proxy_managers_id_seq RESTART WITH 1;
ALTER SEQUENCE service_contract.contract_price_components_id_seq RESTART WITH 1;
ALTER SEQUENCE service_contract.contract_iap_price_components_id_seq RESTART WITH 1;
ALTER SEQUENCE service_contract.contract_related_service_orders_id_seq RESTART WITH 1;
ALTER SEQUENCE service_contract.contract_related_service_contracts_id_seq RESTART WITH 1;
ALTER SEQUENCE service_contract.contract_related_goods_orders_id_seq RESTART WITH 1;
ALTER SEQUENCE service_contract.contract_version_types_id_seq RESTART WITH 1;

ALTER SEQUENCE nomenclature.prefixes_id_seq RESTART WITH 1;
ALTER SEQUENCE company.companies_id_seq RESTART WITH 1;
ALTER SEQUENCE company.company_number_seq RESTART WITH 1;
ALTER SEQUENCE company.company_details_id_seq RESTART WITH 1;
ALTER SEQUENCE company.company_logos_id_seq RESTART WITH 1;
ALTER SEQUENCE company.company_banks_id_seq RESTART WITH 1;
ALTER SEQUENCE company.company_communication_addresses_id_seq RESTART WITH 1;
ALTER SEQUENCE company.company_emails_id_seq RESTART WITH 1;
ALTER SEQUENCE company.company_invoice_compilers_id_seq RESTART WITH 1;
ALTER SEQUENCE company.company_invoice_issue_places_id_seq RESTART WITH 1;
ALTER SEQUENCE company.company_managers_id_seq RESTART WITH 1;
ALTER SEQUENCE company.company_telephones_id_seq RESTART WITH 1;
ALTER SEQUENCE billing.account_periods_id_seq RESTART WITH 1;
ALTER SEQUENCE billing.account_period_status_change_hist_id_seq RESTART WITH 1;
ALTER SEQUENCE billing.billings_id_seq RESTART WITH 1;
ALTER SEQUENCE billing.process_periodicity_id_seq RESTART WITH 1;
ALTER SEQUENCE billing.process_periodicity_day_of_months_id_seq RESTART WITH 1;
ALTER SEQUENCE billing.process_periodicity_incompatible_billings_id_seq RESTART WITH 1;
ALTER SEQUENCE billing.process_periodicity_issuing_periods_id_seq RESTART WITH 1;
ALTER SEQUENCE billing.process_periodicity_period_of_year_id_seq RESTART WITH 1;
ALTER SEQUENCE billing.process_periodicity_start_time_intervals_id_seq RESTART WITH 1;
ALTER SEQUENCE billing.billing_process_periodicity_id_seq RESTART WITH 1;
ALTER SEQUENCE billing.billing_billing_groups_id_seq RESTART WITH 1;
ALTER SEQUENCE billing.billing_summary_data_id_seq RESTART WITH 1;
ALTER SEQUENCE billing.billing_detailed_data_id_seq RESTART WITH 1;
ALTER SEQUENCE billing.billing_tasks_id_seq RESTART WITH 1;
ALTER SEQUENCE billing.billing_invoices_id_seq RESTART WITH 1;
ALTER SEQUENCE invoice.invoices_id_seq RESTART WITH 1;
ALTER SEQUENCE invoice.invoice_detailed_data_id_seq RESTART WITH 1;
ALTER SEQUENCE invoice.invoice_vat_rate_values_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.risk_assessments_id_seq RESTART WITH 1;
ALTER SEQUENCE product_contract.contract_interim_advance_payments_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.pod_measurement_types_id_seq RESTART WITH 1;

ALTER SEQUENCE power_supply_disconnection_reminders_id_seq RESTART WITH 1;
ALTER SEQUENCE power_supply_disconnection_reminder_tasks_id_seq RESTART WITH 1;
ALTER SEQUENCE power_supply_disconnection_reminder_customers_id_seq RESTART WITH 1;
ALTER SEQUENCE receivable.customer_receivables_id_seq RESTART WITH 1;
ALTER SEQUENCE receivable.mlo_customer_receivables_id_seq RESTART WITH 1;
ALTER SEQUENCE receivable.customer_liabilities_id_seq RESTART WITH 1;
ALTER SEQUENCE receivable.mlo_customer_liabilities_id_seq RESTART WITH 1;
ALTER SEQUENCE receivable.late_payment_fine_communications_id_seq RESTART WITH 1;
ALTER SEQUENCE receivable.late_payment_fine_ftp_files_id_seq RESTART WITH 1;
ALTER SEQUENCE receivable.late_payment_fines_id_seq RESTART WITH 1;
ALTER SEQUENCE receivable.mlo_customer_deposits_id_seq RESTART WITH 1;
ALTER SEQUENCE receivable.customer_deposits_id_seq RESTART WITH 1;
ALTER SEQUENCE receivable.payment_packages_id_seq RESTART WITH 1;
ALTER SEQUENCE receivable.manual_liabilitie_offsettings_id_seq RESTART WITH 1;
ALTER SEQUENCE receivable.collection_channels_id_seq RESTART WITH 1;
ALTER SEQUENCE receivable.collection_channel_banks_id_seq RESTART WITH 1;
ALTER SEQUENCE receivable.collection_channel_priority_liab_prefixes_id_seq RESTART WITH 1;
ALTER SEQUENCE receivable.collection_channel_exclude_liab_prefixes_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.cancelation_reasons_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.grounds_for_objection_withdrawal_to_change_of_cbg_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.balancing_group_coordinator_grounds_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.blocking_reasons_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.collection_partners_id_seq RESTART WITH 1;
ALTER SEQUENCE receivable.mass_operation_for_blocking_id_seq RESTART WITH 1;
ALTER SEQUENCE receivable.mass_operation_for_blocking_exclution_prefixes_id_seq RESTART WITH 1;
ALTER SEQUENCE billing.billing_invoice_files_id_seq RESTART WITH 1;
ALTER SEQUENCE receivable.objection_withdrawal_to_change_of_cbg_tasks_id_seq RESTART WITH 1;
ALTER SEQUENCE receivable.objection_withdrawal_to_change_of_cbg_email_templates_id_seq RESTART WITH 1;
ALTER SEQUENCE receivable.objection_withdrawal_to_change_of_cbg_doc_templates_id_seq RESTART WITH 1;
ALTER SEQUENCE receivable.objection_withdrawal_to_change_of_cbg_process_results_id_seq RESTART WITH 1;
ALTER SEQUENCE receivable.objection_withdrawal_to_change_of_cbg_id_seq RESTART WITH 1;

ALTER SEQUENCE nomenclature.sms_sending_numbers_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.rps_numbers_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.communication_topics_id_seq RESTART WITH 1;
ALTER SEQUENCE crm.email_communications_id_seq RESTART WITH 1;
ALTER SEQUENCE process_management.process_files_id_seq RESTART WITH 1;
ALTER SEQUENCE billing.billing_error_data_id_seq RESTART WITH 1;
ALTER SEQUENCE invoice.invoice_reversal_invoice_id_seq RESTART WITH 1;
ALTER SEQUENCE product.product_details_collection_channels_id_seq RESTART WITH 1;
ALTER SEQUENCE service.service_details_collection_channels_id_seq RESTART WITH 1;
ALTER SEQUENCE template.template_details_id_seq RESTART WITH 1;
ALTER SEQUENCE template.templates_id_seq RESTART WITH 1;
ALTER SEQUENCE service.service_template_id_seq RESTART WITH 1;
ALTER SEQUENCE product.product_templates_id_seq RESTART WITH 1;
ALTER SEQUENCE billing.billing_templates_id_seq RESTART WITH 1;
ALTER SEQUENCE template.template_files_id_seq RESTART WITH 1;
ALTER SEQUENCE template.document_id_seq RESTART WITH 1;
ALTER SEQUENCE template.document_file_id_seq RESTART WITH 1;
ALTER SEQUENCE terms.penalty_templates_id_seq RESTART WITH 1;
ALTER SEQUENCE invoice.invoice_cancelation_templates_id_seq RESTART WITH 1;
ALTER SEQUENCE receivable.power_supply_disconnection_reminder_templates_id_seq RESTART WITH 1;
ALTER SEQUENCE receivable.objection_to_change_of_cbg_id_seq RESTART WITH 1;
ALTER SEQUENCE product.termination_templates_id_seq RESTART WITH 1;
ALTER SEQUENCE receivable.objection_to_change_of_cbg_templates_id_seq RESTART WITH 1;
ALTER SEQUENCE receivable.objection_to_change_of_cbg_sub_files_id_seq RESTART WITH 1;
ALTER SEQUENCE receivable.objection_to_change_of_cbg_pods_id_seq RESTART WITH 1;
ALTER SEQUENCE receivable.power_supply_disconnection_request_pods_id_seq RESTART WITH 1;
ALTER SEQUENCE receivable.power_supply_disconnection_request_pod_liabilities_id_seq RESTART WITH 1;
ALTER SEQUENCE process_management.process_notification_id_seq RESTART WITH 1;
ALTER SEQUENCE notification.user_notification_id_seq RESTART WITH 1;

ALTER SEQUENCE invoice.manual_invoice_summary_data_id_seq RESTART WITH 1;
ALTER SEQUENCE invoice.manual_invoice_detailed_data_id_seq RESTART WITH 1;
ALTER SEQUENCE billing.billing_run_draft_invoices_marks_id_seq RESTART WITH 1;
ALTER SEQUENCE billing.billing_run_draft_generated_invoices_marks_id_seq RESTART WITH 1;
ALTER SEQUENCE receivable.power_supply_reconnections_id_seq RESTART WITH 1;
ALTER SEQUENCE receivable.power_supply_reconnection_files_id_seq RESTART WITH 1;
ALTER SEQUENCE receivable.power_supply_reconnection_pods_id_seq RESTART WITH 1;
ALTER SEQUENCE receivable.customer_payment_receivable_offsettings_id_seq RESTART WITH 1;
ALTER SEQUENCE receivable.customer_deposit_payment_deadline_after_withdrawal_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.missing_customer_id_seq RESTART WITH 1;
ALTER SEQUENCE billing.billing_invoice_sum_files_id_seq RESTART WITH 1;
ALTER SEQUENCE invoice.real_invoice_number_seq RESTART WITH 1;
ALTER SEQUENCE invoice.real_proforma_invoice_number_seq RESTART WITH 1;
ALTER SEQUENCE invoice.draft_invoice_number_seq RESTART WITH 1;
ALTER SEQUENCE invoice.draft_proforma_invoice_number_seq RESTART WITH 1;
ALTER SEQUENCE invoice.invoice_number_generator_id_seq RESTART WITH 1;
ALTER SEQUENCE receivable.mlo_customer_negative_payments_id_seq RESTART WITH 1;
ALTER SEQUENCE nomenclature.scales_id_seq  RESTART WITH 1;
ALTER SEQUENCE price_component.am_for_volumes_by_settlement_period_issuing_periods_id_seq  RESTART WITH 1;
ALTER SEQUENCE customer_deposits_id_seq  RESTART WITH 1;
ALTER SEQUENCE customer_liabilities_id_seq  RESTART WITH 1;
ALTER SEQUENCE customer_assessments_id_seq  RESTART WITH 1;
ALTER SEQUENCE customer_assessment_tasks_id_seq  RESTART WITH 1;
ALTER SEQUENCE receivable.late_payment_fine_tasks_id_seq  RESTART WITH 1;
