stages:
  - dependencies
  - build
  - build-docker
  - deploy

variables:
  DOCKER_DRIVER: overlay
  IMAGE_NAME: git.domain.internal/asterbit/phoenix-payment-test-api
  CONTAINER_PORT: 9091
  APP_NAME: phoenix-payment-test-api
  serverUrl: http://10.236.20.31:9091
  profile: test

build:
 # image: gradle:7.3.3-jdk17-alpine

  stage: build
  script:
    - echo "Clean the code..."
    - sudo sh $CI_PROJECT_DIR/gradlew clean --no-daemon
    - echo "Compiling the code..."
    - sudo sh $CI_PROJECT_DIR/gradlew build --no-daemon
  artifacts:
    paths:
      - build/libs/phoenix-payment-api-0.0.1-SNAPSHOT.jar
    expire_in: 1 week
  tags: 
  #  - test-runner-docker
    - test-runner-shell
  needs: ["choose_env"]

build-docker:
  stage: build-docker
  script:
    - sudo docker build -t $IMAGE_NAME .
  tags:
    - test-runner-shell 
  needs: ["build"]

container-deploy:
  stage: deploy
  script:
    - sudo docker rm -f $APP_NAME > /dev/null 2>&1
    - sudo docker run -v /data2:/data -v /phoenix/cert/:/usr/share/certs/ -v /phoenix/jsingpdf/:/usr/share/jsingpdf/ -v /usr/share/fonts:/usr/share/fonts --env serverUrl=$serverUrl --env profile=$profile -d --restart unless-stopped --name $APP_NAME -p $CONTAINER_PORT:8081 $IMAGE_NAME
    - sudo docker system prune -f
  tags:
    - test-runner-shell
  needs: ["build-docker"]
