create schema customerEasyPayTest;
create table if not exists customerEasyPayTest.customers
(
    id                      integer generated by default as identity
        constraint customers_pk
            primary key,
    customer_number         bigint
        constraint customers_uk1
            unique,
    identifier              varchar(13),
    customer_type           varchar(50)                                 not null,
    status                  varchar(50),
    last_customer_detail_id integer
);