package bg.energo.phoenix.model.enums.product.price.priceComponent.applicationModel;

public enum PriceComponentMonthNumber {
    ONE,
    TWO,
    THREE,
    FOUR,
    FIVE,
    SIX,
    SEVEN,
    EIGHT,
    NINE,
    TEEN,
    ELEVEN,
    TWELVE,
    THIRTEEN,
    FOURTEEN,
    FIFTEEN,
    SIXTEEN,
    SEVENTEEN,
    EIGHTTEEN,
    NINETEEN,
    TWENTY,
    TWENTYONE,
    TWENTYTWO,
    TWENTYTHREE,
    TWENTYFOUR,
    TWENTYFIVE,
    TWENTYSIX,
    TWENTYSEVEN,
    TWENTYEIGHT,
    TWENTYNINE,
    THIRT,
    THIRTYONE,
    ALL_DAYS
}
