package bg.energo.phoenix.model.enums.product.iap.interimAdvancePayment;

public enum MonthNumber {
    ONE,
    TWO,
    THREE,
    FOUR,
    FIVE,
    SIX,
    SEVEN,
    EIGHT,
    NINE,
    TEN,
    ELEVEN,
    TWELVE,
    THIRTEEN,
    FOURTEEN,
    FIFTEEN,
    SIXTEEN,
    SEVENTEEN,
    EIGHTEEN,
    NINETEEN,
    TWENTY,
    TWENTYONE,
    TWENTYTWO,
    TWENTYTHREE,
    TWENTYFOUR,
    TWENTYFIVE,
    TWENTYSIX,
    TWENTYSEVEN,
    TWENTYEIGHT,
    TWENTYNINE,
    THIRTY,
    THIRTYONE,
    ALL_DAYS
}
