# logging
logging.level.org.springframework.web=DEBUG
logging.level.bg.energo.phoenix=DEBUG
logging.level.com.watchguard=DEBUG
logging.level.vault=DEBUG
logging.level.org.springdoc=DEBUG
logging.level.bg.energo.migration=DEBUG

# redis config
spring.cache.type=redis
spring.data.redis.host=10.236.20.17
spring.data.redis.port=6379
spring.data.redis.password=7J20YecDOqog
app.cfg.cache.ttl=30
spring.main.lazy-initialization=true
# second level cache
spring.jpa.properties.hibernate.cache.use_query_cache=true
spring.jpa.properties.hibernate.cache.use_second_level_cache=true
spring.jpa.properties.hibernate.cache.region.factory_class=jcache
spring.jpa.properties.hibernate.javax.cache.provider=org.ehcache.jsr107.EhcacheCachingProvider
spring.jpa.properties.hibernate.javax.cache.uri=jcache.xml
# sql config
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.query.function.SqlFunctionsMetadataBuilderContributor=bg.energo.phoenix.config.SQLFunctionContributor
# Locale
spring.web.locale=en_US
