spring.application.name=migration
spring.profiles.active=${profile:local}
spring.web.locale=en_US
spring.data.redis.repositories.enabled=false
spring.main.lazy-initialization=true
server.port=8084
logging.file.name=logs/app.log