stages:
    - choose_env
    - approve_stage
    - dependencies
    - build
    - build-docker
    - deploy

choose_env:
  stage: choose_env
  script:
    - echo "approved"
  tags:
    - dev-runner-shell

include:
     - local: 'pipelines/dev-pipeline.yml'
       rules:
         - if: '$CI_COMMIT_BRANCH == "dev"'

     - local: 'pipelines/dev2-pipeline.yml'
       rules:
         - if: '$CI_COMMIT_BRANCH == "dev2"'

     - local: 'pipelines/feature-pipeline.yml'
       rules:
         - if: '$CI_COMMIT_BRANCH =~ /^feature\//'

     - local: 'pipelines/pre-pipeline.yml'
       rules:
         - if: '$CI_COMMIT_BRANCH == "pre-prod"'

     - local: 'pipelines/prod-pipeline.yml'
       rules:
         - if: '$CI_COMMIT_BRANCH == "prod"'

     - local: 'pipelines/test-pipeline.yml'
       rules:
         - if: '$CI_COMMIT_BRANCH == "test"'
