package bg.energo.phoenix.model.enums.customer.filter;

import lombok.Getter;

public enum CustomerSearchFields {
    ALL("ALL"),
    ID("IDENTIFIER"),
    PERSONAL_NUMBER("PERSONAL_NUMBER"),
    NAME("CUSTOMERNAME"),
    NAME_LEGAL_ENTITY("NAME_OF_LEGAL_ENTITY"),
    MIDDLE_NAME("CUSTOMERMIDDLENAME"),
    LAST_NAME("CUSTOMERLASTENAME"),
    COUNTRY_NAME("COUNTRY"),
    REGION_NAME("REGION"),
    MUNICIPALITY_NAME("MUNICIPALITY"),
    DISTRICT_NAME("DISTRICT"),
    STREET_NAME("STREET"),
    RESIDENTIAL_AREA_NAME("RESIDENTIALAREA"),
    MANAGER_NAME("CUSTOMERMANAGER_NAME"),
    MANAGER_MIDDLE_NAME("CUSTOMERMANAGER_MIDDLE_NAME"),
    MANAGER_LAST_NAME("CUSTOMERMANAGER_LAST_NAME"),
    ACCOUNT_MANAGER_NAME("ACCOUNT_MANAGER_NAME"),
    ACCOUNT_MANAGER_ORG_UNIT("ACCOUNT_MANAGER_ORG_UNIT"),
    ACCOUNT_MANAGER_BUS_UNIT("ACCOUNT_MANAGER_BUS_UNIT"),
    ACCOUNT_MANAGER_DISPLAY_NAME("ACCOUNT_MANAGER_DISPLAY_NAME");

    @Getter
    private String value;

    CustomerSearchFields(String value) {
        this.value = value;
    }
}
