stages:
    - choose_env
    - approve_stage
    - dependencies
    - build
    - build-docker
    - deploy
    - notify

choose_env:
  stage: choose_env
  script:
    - echo "approved"
  tags:
    - dev-runner-shell

include:
     - local: 'pipelines/dev-pipeline.yml'
       rules:
         - if: '$CI_COMMIT_BRANCH == "dev"'


     - local: 'pipelines/test-pipeline.yml'
       rules:
         - if: '$CI_COMMIT_BRANCH == "test"'

     - local: 'pipelines/sep-pipeline.yml'
       rules:
         - if: '$CI_COMMIT_BRANCH == "sep_release"'

     - local: 'pipelines/prod-pipeline.yml'
       rules:
         - if: '$CI_COMMIT_BRANCH == "main"'



     - local: 'pipelines/prod-pipeline.yml'
       rules:
         - if: '$CI_COMMIT_BRANCH =~ /^release\//'



     - local: 'pipelines/feature-pipeline.yml'
       rules:
         - if: '$CI_COMMIT_BRANCH =~ /^feature\//'