package bg.energo.phoenix.process.model.enums;

public enum ProcessType {
    PROCESS_CUSTOMER_MASS_IMPORT,
    PROCESS_UNWANTED_CUSTOMER_MASS_IMPORT,
    PROCESS_POD_MASS_IMPORT,
    PROCESS_PRODUCT_MASS_IMPORT,
    PROCESS_SERVICE_MASS_IMPORT,
    PROCESS_METER_MASS_IMPORT,
    PROCESS_SUPPLY_AUTOMATIC_ACTIVATION_MASS_IMPORT,
    PROCESS_SUPPLY_AUTOMATIC_DEACTIVATION_MASS_IMPORT,
    PROCESS_SUPPLY_ACTION_DEACTIVATION_MASS_IMPORT,
    PRODUCT_CONTRACT_MASS_IMPORT,
    PROCESS_SERVICE_CONTRACT_MASS_IMPORT,
    PROCESS_INVOICE_CANCELLATION,
    X_ENERGIE_EXCEPTION_REPORT,
    PROCESS_CUSTOMER_RECEIVABLE_MASS_IMPORT,
    PROCESS_CUSTOMER_LIABILITY_MASS_IMPORT,
    PROCESS_PAYMENT_MASS_IMPORT,
    PROCESS_REMINDER,
    GOVERNMENT_COMPENSATION_MASS_IMPORT;
}
