INSERT INTO nomenclature.currencies (id, name, print_name, abbreviation, full_name, alt_currency_id,
                                     alt_ccy_exchange_rate, main_ccy_start_date, main_ccy, is_default, create_date,
                                     system_user_id, modify_date, modify_system_user_id, status, ordering_id)
VALUES (26,
        'EUR',
        'EUR',
        'euro',
        'EURO',
        null,
        2,
        '2024-08-01',
        true,
        true,
        '2023-03-23 11:45:08.533576 +00:00',
        'm47500',
        '2024-10-17 12:46:08.360461 +00:00',
        'phoenix.testa',
        'ACTIVE',
        39);

INSERT INTO nomenclature.currencies (id, name, print_name, abbreviation, full_name, alt_currency_id,
                                     alt_ccy_exchange_rate, main_ccy_start_date, main_ccy, is_default, create_date,
                                     system_user_id, modify_date, modify_system_user_id, status, ordering_id)
VALUES (61,
        'лева',
        'лева',
        'лв.',
        'Български лев',
        26,
        0.5,
        null,
        false,
        false,
        '2023-03-27 11:04:09.382525 +00:00',
        'm47500',
        '2024-10-17 12:46:08.376111 +00:00',
        'phoenix.testa',
        'ACTIVE',
        99);

update nomenclature.currencies
set alt_currency_id = 61
where id = 26;

INSERT INTO nomenclature.vat_rates (id, name, value_in_percent, start_date, global_vat_rate, create_date,
                                    system_user_id, modify_date, modify_system_user_id, status, ordering_id)
VALUES (327,
        'LUKAS VAT RATE (10%)',
        10,
        null,
        false,
        '2024-03-18 09:16:50.784634 +00:00',
        'phoenix.testa',
        '2024-10-04 11:32:44.896894 +00:00',
        'l13943',
        'ACTIVE',
        151);

INSERT INTO billing_run.run_interim_data (id, is_valid_for_generation, run_id, run_interim_contract_id,
                                          billing_group_id,
                                          pod_id, interim_id, interim_from_type, value_type, valid_for_value_type,
                                          calculation_value, currency_id, date_of_issue_type,
                                          valid_for_date_of_issue_type, date_of_issue_value,
                                          has_valid_payment_term_value, payment_term_value, payment_term_id,
                                          price_component_id, issued_separate_invoice, valid_for_days_after_invoice,
                                          vat_rate_id, prev_invoice_id, status, contract_id, contract_detail_id,
                                          product_detail_id, contract_type, error_message, product_id,
                                          issuing_for_the_month_to_current, deduction_from, global_vat_rate,
                                          price_formula, match_term_of_standard_invoice, customer_detail_id,
                                          cost_center_controlling_order, number_of_income_account,
                                          applicable_interest_rate, direct_debit, bank_id, bank_account,
                                          receipt_of_an_invoice_number, customer_communication_id,
                                          contract_communication_id, no_interest_on_overdue_debt)
VALUES (1,
        true,
        8957,
        432948,
        8158,
        null,
        4580,
        'DIRECT',
        'EXACT_AMOUNT',
        true,
        5,
        26,
        'PERIODICAL',
        true,
        null,
        true,
        null,
        null,
        null,
        'INVOICE_ONE',
        null,
        327,
        null,
        'SUCCESS',
        26736,
        11997,
        6708,
        'PRODUCT_CONTRACT',
        null,
        4792,
        'ZERO',
        'FIRST_INVOICE_WITH_LONGER_PAYMENT_TERM',
        false,
        null,
        true,
        174526321,
        '1',
        '1',
        803,
        true,
        426,
        'BG12AAAA121212AAAA1212',
        174526321,
        null,
        15995,
        false);
