plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.2'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'bg.energo'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '17'

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}
def eproSnapshotDomain = "https://nexus.energo-pro.bg//repository/epro-maven-snapshots/"
def eproReleaseDomain = "https://nexus.energo-pro.bg/repository/epro-maven-releases/"
def profile = project.hasProperty('profile') ? project.getProperty('profile') : 'dev'
def devVersion = '1.39.81-SNAPSHOT'
def testVersion = '0.0.26'


ext {
    liquibaseGradlePluginVersion = '2.1.1'
    postgresqlVersion = '42.5.1'
    liquibaseCore = '4.16.1'
    lombokVersion = '1.18.24'
    openApiVersion = '2.5.0'
    openhtmlVersion = '1.0.5'
    iban4jVersion = '3.2.3-RELEASE'
    springCloudVersion = '2023.0.2'
    coreLibVersion = (profile in ['test', 'preProd','prod']) ? testVersion : devVersion
}
dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
        mavenBom "org.springframework.boot:spring-boot-dependencies:3.3.2"
        mavenBom "org.testcontainers:testcontainers-bom:1.21.4"

    }
}
repositories {
    mavenCentral()
    mavenLocal()
    maven {
        url eproSnapshotDomain
    }
    maven {
        url eproReleaseDomain
    }
    maven {
        url "https://releases.aspose.com/java/repo/"
        allowInsecureProtocol = true
    }
}
dependencies {
    implementation group: "bg.energo", name: "phoenix-core-lib2", version: "${coreLibVersion}"
    implementation 'org.springframework.boot:spring-boot-starter-websocket'

    testImplementation 'org.springframework.cloud:spring-cloud-starter-bootstrap'
    testImplementation 'org.springframework.cloud:spring-cloud-starter'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'
    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation 'org.testcontainers:postgresql'
    testImplementation group: 'org.wiremock', name: 'wiremock-standalone', version: '3.2.0'
    implementation 'com.aspose:aspose-cells:23.8'
    implementation 'com.aspose:aspose-cells:23.8:javadoc'
    implementation 'com.ibm.icu:icu4j:74.2'
    compileOnly 'org.projectlombok:lombok'

    testAnnotationProcessor "org.projectlombok:lombok"

    testCompileOnly 'org.projectlombok:lombok'

    annotationProcessor 'org.projectlombok:lombok'
}

test {
    jvmArgs '-Xmx2g'
    timeout = Duration.ofMinutes(30)
    // todo change back when pipeline is fixed!
}

tasks.named('test') {
    useJUnitPlatform()
}

