package bg.energo.phoenix.model.request.product.product;

import bg.energo.phoenix.model.enums.product.product.*;
import lombok.Builder;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Set;

public class ProductCreateRequest extends BaseProductRequest {
    @Builder
    public ProductCreateRequest(Boolean isIndividual,
                                String customerIdentifier,
                                Long consumerBalancingProductNameId,
                                Long generatorBalancingProductNameId,
                                String name,
                                String nameTransliterated,
                                String printingName,
                                String printingNameTransliterated,
                                ProductDetailStatus productStatus,
                                Boolean availableForSale,
                                LocalDateTime availableFrom,
                                LocalDateTime availableTo,
                                String shortDescription,
                                String fullDescription,
                                List<BaseProductTermsRequest> productTerms,
                                Long productGroupId,
                                String otherSystemConnectionCode,
                                Long productTypeId,
                                Set<ContractType> contractTypes,
                                Set<PaymentGuarantee> paymentGuarantees,
                                BigDecimal cashDepositAmount,
                                Long cashDepositCurrencyId,
                                BigDecimal bankGuaranteeAmount,
                                Long bankGuaranteeCurrencyId,
                                Set<PurposeOfConsumption> purposeOfConsumptions,
                                Set<MeteringTypeOfThePointOfDelivery> meteringTypeOfThePointOfDeliveries,
                                Set<VoltageLevel> voltageLevels,
                                Set<ProductPodType> typePointsOfDelivery,
                                List<Long> gridOperatorIds,
                                String invoiceAndTemplatesText,
                                String invoiceAndTemplatesTextTransliterated,
                                String incomeAccountNumber,
                                String costCenterControllingOrder,
                                Boolean globalVatRate,
                                Long vatRateId,
                                Boolean globalSalesChannel,
                                List<Long> salesChannelIds,
                                Boolean globalSalesAreas,
                                List<Long> salesAreasIds,
                                Boolean globalSegment,
                                List<Long> segmentIds,
                                Long electricityPriceTypeId,
                                Boolean equalMonthlyInstallmentsActivation,
                                Short installmentNumber,
                                Short installmentNumberFrom,
                                Short installmentNumberTo,
                                BigDecimal amount,
                                BigDecimal amountFrom,
                                BigDecimal amountTo,
                                Long currencyId,
                                Set<ScheduleRegistrations> scheduleRegistrations,
                                Set<Forecasting> forecasting,
                                Set<TakingOverBalancingCosts> takingOverBalancingCosts,
                                ProvidedCapacityLimitType capacityLimitType,
                                Short capacityLimitAmount,
                                List<Long> collectionChannels,
                                Long termId,
                                Long termGroupId,
                                List<Long> terminationIds,
                                List<Long> terminationGroupIds,
                                List<Long> penaltyIds,
                                List<Long> penaltyGroupIds,
                                List<Long> priceComponentIds,
                                List<Long> priceComponentGroupIds,
                                List<Long> interimAdvancePayments,
                                List<Long> interimAdvancePaymentGroups,
                                String additionalInfo1,
                                String additionalInfo2,
                                String additionalInfo3,
                                String additionalInfo4,
                                String additionalInfo5,
                                String additionalInfo6,
                                String additionalInfo7,
                                String additionalInfo8,
                                String additionalInfo9,
                                String additionalInfo10,
                                List<ProductRelatedEntityRequest> relatedEntities,
                                List<Long> productFileIds,
                                Boolean globalGridOperator,
                                List<ProductsAdditionalParamsRequest> productsAdditionalParams,
                                Set<TemplateSubObjectRequest> templateIds) {
        super(isIndividual,
                customerIdentifier,
                consumerBalancingProductNameId,
                generatorBalancingProductNameId,
                name,
                nameTransliterated,
                printingName,
                printingNameTransliterated,
                productStatus,
                availableForSale,
                availableFrom,
                availableTo,
                shortDescription,
                fullDescription,
                productTerms,
                productGroupId,
                otherSystemConnectionCode,
                productTypeId,
                contractTypes,
                paymentGuarantees,
                cashDepositAmount,
                cashDepositCurrencyId,
                bankGuaranteeAmount,
                bankGuaranteeCurrencyId,
                purposeOfConsumptions,
                meteringTypeOfThePointOfDeliveries,
                voltageLevels,
                typePointsOfDelivery,
                globalGridOperator,
                gridOperatorIds,
                invoiceAndTemplatesText,
                invoiceAndTemplatesTextTransliterated,
                incomeAccountNumber,
                costCenterControllingOrder,
                globalVatRate,
                vatRateId,
                globalSalesChannel,
                salesChannelIds,
                globalSalesAreas,
                salesAreasIds,
                globalSegment,
                segmentIds,
                electricityPriceTypeId,
                equalMonthlyInstallmentsActivation,
                installmentNumber,
                installmentNumberFrom,
                installmentNumberTo,
                amount,
                amountFrom,
                amountTo,
                currencyId,
                scheduleRegistrations,
                forecasting,
                takingOverBalancingCosts,
                capacityLimitType,
                capacityLimitAmount,
                collectionChannels,
                termId,
                termGroupId,
                terminationIds,
                terminationGroupIds,
                penaltyIds,
                penaltyGroupIds,
                priceComponentIds,
                priceComponentGroupIds,
                interimAdvancePayments,
                interimAdvancePaymentGroups,
                additionalInfo1,
                additionalInfo2,
                additionalInfo3,
                additionalInfo4,
                additionalInfo5,
                additionalInfo6,
                additionalInfo7,
                additionalInfo8,
                additionalInfo9,
                additionalInfo10,
                relatedEntities,
                productFileIds,
                productsAdditionalParams,templateIds);
    }
}
