package bg.energo.phoenix.model.enums.task;

public enum TaskSubObjectType {
    CUSTOMER,
    CUSTOMER_ASSESSMENT,
    PRODUCT_CONTRACT,
    SERVICE_CONTRACT,
    GOODS_ORDER,
    SERVICE_ORDER,
    BILLING,
    RECEIVABLE_BLOCKING,
    EMAIL_COMMUNICATION,
    MASS_EMAIL_COMMUNICATION,
    SMS_COMMUNICATION,
    MASS_SMS_COMMUNICATION,
    DISCONNECTION_POWER_SUPPLY_REQUESTS,
    RECONNECTION_OF_POWER_SUPPLY,
    CANCELLATION_OF_REQUEST_FOR_DISCONNECTION_OF_PWS,
    DISCONNECTION_OF_POWER_SUPPLY,
    RESCHEDULING,
    LATE_PAYMENT_FINE,
    OBJECTION_TO_CHANGE_OF_CBG,
    OBJECTION_WITHDRAWAL_TO_CHANGE_OF_CBG,
    REMINDER_FOR_DISCONNECTION_OF_PWS
}
